
package fr.afcepf.al32.devise.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import fr.afcepf.al32.devise.itf.Devise;
import fr.afcepf.al32.devise.itf.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IServiceDevise", targetNamespace = "http://itf.devise.al32.afcepf.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IServiceDevise {


    /**
     * 
     * @param monnaie
     * @return
     *     returns fr.afcepf.al32.devise.itf.Devise
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDevise", targetNamespace = "http://itf.devise.al32.afcepf.fr/", className = "fr.afcepf.al32.devise.itf.GetDevise")
    @ResponseWrapper(localName = "getDeviseResponse", targetNamespace = "http://itf.devise.al32.afcepf.fr/", className = "fr.afcepf.al32.devise.itf.GetDeviseResponse")
    @Action(input = "http://itf.devise.al32.afcepf.fr/IServiceDevise/getDeviseRequest", output = "http://itf.devise.al32.afcepf.fr/IServiceDevise/getDeviseResponse")
    public Devise getDevise(
        @WebParam(name = "monnaie", targetNamespace = "")
        String monnaie);

    /**
     * 
     * @param monnaieCible
     * @param montant
     * @param monnaieSource
     * @return
     *     returns java.lang.Double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "convertir", targetNamespace = "http://itf.devise.al32.afcepf.fr/", className = "fr.afcepf.al32.devise.itf.Convertir")
    @ResponseWrapper(localName = "convertirResponse", targetNamespace = "http://itf.devise.al32.afcepf.fr/", className = "fr.afcepf.al32.devise.itf.ConvertirResponse")
    @Action(input = "http://itf.devise.al32.afcepf.fr/IServiceDevise/convertirRequest", output = "http://itf.devise.al32.afcepf.fr/IServiceDevise/convertirResponse")
    public Double convertir(
        @WebParam(name = "montant", targetNamespace = "")
        Double montant,
        @WebParam(name = "monnaieSource", targetNamespace = "")
        String monnaieSource,
        @WebParam(name = "monnaieCible", targetNamespace = "")
        String monnaieCible);

}
