
package fr.afcepf.al32.devise.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServiceDeviseImplService", targetNamespace = "http://impl.devise.al32.afcepf.fr/", wsdlLocation = "http://localhost:8080/servSoap/serviceDevise?wsdl")
public class ServiceDeviseImplService
    extends Service
{

    private final static URL SERVICEDEVISEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICEDEVISEIMPLSERVICE_EXCEPTION;
    private final static QName SERVICEDEVISEIMPLSERVICE_QNAME = new QName("http://impl.devise.al32.afcepf.fr/", "ServiceDeviseImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/servSoap/serviceDevise?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICEDEVISEIMPLSERVICE_WSDL_LOCATION = url;
        SERVICEDEVISEIMPLSERVICE_EXCEPTION = e;
    }

    public ServiceDeviseImplService() {
        super(__getWsdlLocation(), SERVICEDEVISEIMPLSERVICE_QNAME);
    }

    public ServiceDeviseImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICEDEVISEIMPLSERVICE_QNAME, features);
    }

    public ServiceDeviseImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICEDEVISEIMPLSERVICE_QNAME);
    }

    public ServiceDeviseImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICEDEVISEIMPLSERVICE_QNAME, features);
    }

    public ServiceDeviseImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceDeviseImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IServiceDevise
     */
    @WebEndpoint(name = "ServiceDeviseImplPort")
    public IServiceDevise getServiceDeviseImplPort() {
        return super.getPort(new QName("http://impl.devise.al32.afcepf.fr/", "ServiceDeviseImplPort"), IServiceDevise.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IServiceDevise
     */
    @WebEndpoint(name = "ServiceDeviseImplPort")
    public IServiceDevise getServiceDeviseImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.devise.al32.afcepf.fr/", "ServiceDeviseImplPort"), IServiceDevise.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICEDEVISEIMPLSERVICE_EXCEPTION!= null) {
            throw SERVICEDEVISEIMPLSERVICE_EXCEPTION;
        }
        return SERVICEDEVISEIMPLSERVICE_WSDL_LOCATION;
    }

}
