
Gsrc/main/java/org/mybatis/jpetstore/web/actions/AbstractActionBean.java
7src/main/java/org/mybatis/jpetstore/domain/Account.java
Fsrc/main/java/org/mybatis/jpetstore/web/actions/AccountActionBean.java
=src/main/java/org/mybatis/jpetstore/mapper/AccountMapper.java
?src/main/java/org/mybatis/jpetstore/service/AccountService.java
.src/main/webapp/WEB-INF/applicationContext.xml
4src/main/java/org/mybatis/jpetstore/domain/Cart.java
Csrc/main/java/org/mybatis/jpetstore/web/actions/CartActionBean.java
8src/main/java/org/mybatis/jpetstore/domain/CartItem.java
Fsrc/main/java/org/mybatis/jpetstore/web/actions/CatalogActionBean.java
?src/main/java/org/mybatis/jpetstore/service/CatalogService.java
8src/main/java/org/mybatis/jpetstore/domain/Category.java
>src/main/java/org/mybatis/jpetstore/mapper/CategoryMapper.java
4src/main/java/org/mybatis/jpetstore/domain/Item.java
:src/main/java/org/mybatis/jpetstore/mapper/ItemMapper.java
8src/main/java/org/mybatis/jpetstore/domain/LineItem.java
>src/main/java/org/mybatis/jpetstore/mapper/LineItemMapper.java
5src/main/java/org/mybatis/jpetstore/domain/Order.java
Dsrc/main/java/org/mybatis/jpetstore/web/actions/OrderActionBean.java
;src/main/java/org/mybatis/jpetstore/mapper/OrderMapper.java
=src/main/java/org/mybatis/jpetstore/service/OrderService.java
pom.xml
7src/main/java/org/mybatis/jpetstore/domain/Product.java
=src/main/java/org/mybatis/jpetstore/mapper/ProductMapper.java
8src/main/java/org/mybatis/jpetstore/domain/Sequence.java
>src/main/java/org/mybatis/jpetstore/mapper/SequenceMapper.java
src/main/webapp/WEB-INF/web.xml